name: Deploy NestJS to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install 

      - run: npx prisma generate

      - run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            dist
            prisma
            package.json
            package-lock.json
            tsconfig.json
            tsconfig.build.json

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app

      - name: Install dependencies
        run: npm install --production

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_26526A137BB74C28BD0C0F803D7023A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B5D67C0D36874C129969E9AD8DCBEB6B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A0327FE8B16244FFA56D281F9A960C78 }}

      - uses: azure/webapps-deploy@v3
        with:
          app-name: Crowdsourced-Collection-Recycling-Platform
          package: .